Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Assignment_5.Models;
namespace Assignment_5.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using Assignment_5.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

//Piece of logic we can reuse and drop somewhere into specified pages
namespace Assignment_5.Components
{
    public class NavigationMenuViewComponent : ViewComponent 
    {

        private IBookstoreRepository repository;

        //constructor
        public NavigationMenuViewComponent (IBookstoreRepository r)
        {
            repository = r;
        }
        //Get a list of items from the repository
        public IViewComponentResult Invoke()
        {
            //Helps with highlighting whatever link is seleted
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(repository.Projects
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Views/Shared/ProjectSummary.cshtml
@model Project

<div class="row">
    <div class="ol-md-8 mx-auto card card-outline-primary m-2 p-3 container container-fluid border border-info">
        <h3>@Model.Title</h3>
        <p>Author: <b>@Model.FirstName @Model.LastName</b></p>
        <p>Publisher: <b>@Model.Publisher</b></p>
        <p>ISBN: <b>@Model.ISBN</b></p>
        <p>Classification/Category: <b>@Model.Classification, @Model.Category</b></p>
        <p>Number of Pages: <b>@Model.PageNumbers</b></p>
        <div class="alert alert-success" role="alert">
            <p>Price: <b>@Model.Price</b></p>
        </div>
        <form id="@Model.BookId" asp-page="/Donate" method="post">
            <!--Sets bookid for this input-->
            <input type="hidden" asp-for="BookId" />
            <!---->
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text p-1">
                <!--Button for Cart-->
                <button type="submit" class="btn-success btn-sm" style="float:inherit">
                    Add to Cart
                </button>
            </span>
        </form>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<!--This will be the layout page. It will act as the template that every page will share-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment_5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>''
<div class="bg-transparent">
    <body>
        <div class="bg-dark text-white p-2">
            <div class="container-fluid">
                <div class="row">
                    <div class="col navbar-brand">SPORTS STORE</div>
                    <div class="col-6 text-right">
                        <vc:cart-summary />
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="jumbotron">
            <h1 class="text-center display-1">Online Bookstore</h1>
            <p class="text-center lead">Welcome to the Bookstore! Below, you can find our most popular books.</p>
            <hr />
        </div>
        <img src="~/img/book_pic.png" class="rounded mx-auto d-block" />
        <!--Get the view component-->
        <vc:navigation-menu />
        <!--At this point, this is where the page will add its personalized content-->
        <div>
            @RenderBody()
        </div>
    </body>
</div>
</html>